# Copyright (C) 2019 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

CXX = icc
CXXFLAGS = $(EXTRA_CXXFLAGS) -std=c++11 -O2
LIBS = -ltbb

# \
!ifndef 0   # \
all clean:  _printmsg # \
# \
_printmsg:  # \
	@echo "for nmake, please specify /f Makefile.nmake"
# \
!else

.PHONY : all clean fig_17_01 fig_17_02 fig_17_03 fig_17_04 fig_17_05 fig_17_08 fig_17_09 fig_17_10 fig_17_11 fig_17_12 fig_17_13 fig_17_15 fig_17_16 fig_17_17 fig_17_19 fig_17_21 fig_17_22 fig_17_23 fig_17_26 fig_17_27 fig_17_28 fig_17_30 fig_17_31 fig_17_33

all : fig_17_01 fig_17_02 fig_17_03 fig_17_04 fig_17_05 fig_17_08 fig_17_09 fig_17_10 fig_17_11 fig_17_12 fig_17_13 fig_17_15 fig_17_16 fig_17_17 fig_17_19 fig_17_21 fig_17_22 fig_17_23 fig_17_26 fig_17_27 fig_17_28 fig_17_30 fig_17_31 fig_17_33

fig_17_01 : 
	$(CXX) $(CXXFLAGS) -o fig_17_01 fig_17_01.cpp $(LIBS)

fig_17_02 : 
	$(CXX) $(CXXFLAGS) -o fig_17_02 fig_17_02.cpp $(LIBS)

fig_17_03 : 
	$(CXX) $(CXXFLAGS) -o fig_17_03 fig_17_03.cpp $(LIBS)

fig_17_04 : 
	$(CXX) $(CXXFLAGS) -o fig_17_04 fig_17_04.cpp $(LIBS)

fig_17_05 : 
	$(CXX) $(CXXFLAGS) -o fig_17_05 fig_17_05.cpp $(LIBS)

fig_17_08 : 
	$(CXX) $(CXXFLAGS) -o fig_17_08 fig_17_08.cpp $(LIBS)

fig_17_09 : 
	$(CXX) $(CXXFLAGS) -o fig_17_09 fig_17_09.cpp $(LIBS)

fig_17_10 : 
	$(CXX) $(CXXFLAGS) -o fig_17_10 fig_17_10.cpp $(LIBS)

fig_17_11 : 
	$(CXX) $(CXXFLAGS) -o fig_17_11 fig_17_11.cpp $(LIBS)

fig_17_12 : 
	$(CXX) $(CXXFLAGS) -o fig_17_12 fig_17_12.cpp $(LIBS)

fig_17_13 : 
	$(CXX) $(CXXFLAGS) -o fig_17_13 fig_17_13.cpp $(LIBS)

fig_17_15 : 
	$(CXX) $(CXXFLAGS) -o fig_17_15 fig_17_15.cpp $(LIBS)

fig_17_16 : 
	$(CXX) $(CXXFLAGS) -o fig_17_16 fig_17_16.cpp $(LIBS)

fig_17_17 : 
	$(CXX) $(CXXFLAGS) -o fig_17_17 fig_17_17.cpp $(LIBS)

fig_17_19 : 
	$(CXX) $(CXXFLAGS) -o fig_17_19 fig_17_19.cpp $(LIBS)

fig_17_21 : 
	$(CXX) $(CXXFLAGS) -o fig_17_21 fig_17_21.cpp $(LIBS)

fig_17_22 : 
	$(CXX) $(CXXFLAGS) -o fig_17_22 fig_17_22.cpp $(LIBS)

fig_17_23 : 
	$(CXX) $(CXXFLAGS) -o fig_17_23 fig_17_23.cpp $(LIBS)

fig_17_26 : 
	$(CXX) $(CXXFLAGS) -o fig_17_26 fig_17_26.cpp $(LIBS)

fig_17_27 : 
	$(CXX) $(CXXFLAGS) -o fig_17_27 fig_17_27.cpp $(LIBS)

fig_17_28 : 
	$(CXX) $(CXXFLAGS) -o fig_17_28 fig_17_28.cpp $(LIBS)

fig_17_30 : 
	$(CXX) $(CXXFLAGS) -o fig_17_30 fig_17_30.cpp $(LIBS)

fig_17_31 : 
	$(CXX) $(CXXFLAGS) -o fig_17_31 fig_17_31.cpp $(LIBS)

fig_17_33 : 
	$(CXX) $(CXXFLAGS) -o fig_17_33 fig_17_33.cpp $(LIBS)

clean : 
	rm -f fig_17_01 fig_17_02 fig_17_03 fig_17_04 fig_17_05 fig_17_08 fig_17_09 fig_17_10 fig_17_11 fig_17_12 fig_17_13 fig_17_15 fig_17_16 fig_17_17 fig_17_19 fig_17_21 fig_17_22 fig_17_23 fig_17_26 fig_17_27 fig_17_28 fig_17_30 fig_17_31 fig_17_33 fig_17_01.o fig_17_02.o fig_17_03.o fig_17_04.o fig_17_05.o fig_17_08.o fig_17_09.o fig_17_10.o fig_17_11.o fig_17_12.o fig_17_13.o fig_17_15.o fig_17_16.o fig_17_17.o fig_17_19.o fig_17_21.o fig_17_22.o fig_17_23.o fig_17_26.o fig_17_27.o fig_17_28.o fig_17_30.o fig_17_31.o fig_17_33.o *.bmp *.txt out*.png


# \
!endif
